---
- name: Create EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: yes  # Necesario para ansible_date_time
  vars:
    aws_region: "{{ aws_region }}"
    key_pair: "{{ key_pair }}"
    security_group_id: "{{ security_group_id }}"
    subnet_id: "{{ subnet_id }}"
    storage_size: "{{ storage_size }}"

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        key_name: "{{ key_pair }}"
        instance_type: t2.micro
        image_id: "{{ image_id }}"
        vpc_subnet_id: "{{ subnet_id }}"
        security_groups: "{{ security_group_id }}"
        volumes:
          - device_name: /dev/xvda
            ebs:
              volume_size: "{{ storage_size }}"
              volume_type: gp3
        network:
          assign_public_ip: yes
        state: running
        count: 1
        tags:
          CreatedOn: "{{ ansible_date_time.iso8601 }}"
      register: ec2_instance

    - name: Display EC2 instance details
      debug:
        msg: ec2_instance
