---
- name: Deploy Dynatrace OneAgent
  hosts: all
  ansible_user: root
  ansible_become: false
  collections:
    - dynatrace.oneagent
  vars_files:
    - encrypted_credentials.yml
  vars:
    oneagent_download_dir: /tmp/oneagent
    oneagent_install_args:
      - --set-host-group=my_host_group
      - --set-monitoring-mode=full-stack
    oneagent_version: latest
  tasks:
    - name: Import OneAgent role
      ansible.builtin.import_role:
        name: oneagent
