---
- name: restart service nginx
  hosts: all
  become: yes
  tasks:
    - name: Reload service nginx, in all cases
      ansible.builtin.systemd_service:
        name: nginx
        state: reloaded
